config {
  type: "view",
  schema: "aal_demo_devday_2026",
  tags: ["staging"],
  description: "Silver Layer: Cleaned and standardized questions from StackOverflow"
}

-- Silver Layer (Staging): Light transformations and standardization

SELECT
    id AS post_id,
    creation_date AS created_at,
    'question' AS type,
    title,
    body,
    owner_user_id,
    NULL AS parent_id
FROM
    ${ref("bigquery-public-data", "stackoverflow", "posts_questions")}
WHERE
    creation_date > '2008-01-01'
